name: issy custom action 

description: Greets someone

inputs: 
  who-to-greet: 
    description: Who to Greet
    required: true
    default: Hello

outputs: 
  time: 
    description: The time we greeted you

runs:
  using: 'node20'
  main: 'dist/index.js'